version: "3.7"

services: 
  db:
    container_name: manabie_db
    image: postgres
    environment: 
      POSTGRES_USER: manabie_postgres
      POSTGRES_PASSWORD: thisisatest
      POSTGRES_DB: manabie_postgres
    volumes:
      - ./init-db/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql 
    ports: 
      - "5432:5432"
    
      
